version: '2'

jobs:
  build:
    docker:
      - image: node:13.13.0-alpine3.10
    steps:
      - checkout

      - setup_remote_docker:

      - run:
        name: Install Docker client
        command: apk add docker-cli
      
      - run: |
      docker build -t anime-api:1.0 .
      docker run anime-api:1.0 npm test


