version: '2'

jobs:
  build:
    working_directory: -/anime-api
    machine:
      - image: ubuntu-1604:202004-01
    steps:
      - checkout
      
      - run: |
      docker build -t anime-api:1.0 .
      docker container run anime-api:1.0 npm test


