version: '3.1'

services:
  anime-api:
    build: .
    image: anime-api
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: mongo:3.6.17-xenial
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db
volumes:
  db-data:
